### ISSUE TITLE
Allow filtering of events in MouseInteraction

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/bqplot-image-gl#42]
To avoid too much communication between the frontend and Python in MouseInteraction, I wonder if it might make sense to pre-filter what kind of events one is interested in, e.g.:

```
interact = MouseInteraction(..., events=['click', 'keydown'])
```

Otherwise when one is not interested in e.g. move events there is unnecessary constant communication.

**Comment by maartenbreddels** [comment]
I agree that would be good. But also in light of https://github.com/bqplot/bqplot/pull/1066#issuecomment-781199254 I wonder if this should go upstream, and then move into Figure, and then indeed have similar to ipyevents a list of events one wants to listen to.
